routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/payment/overdue', 'PaymentController@overdue')->name("payment.overdue");
Route::get('/credit-applications/pending', 'CreditApplicationController@pending')->name('credit-applications.pending');
Route::get('/credit-applications/approve/{credit_application}', 'CreditApplicationController@approve')->name('credit-applications.approve');
Route::post('/credit-applications/approve/{credit_application}/success', 'CreditApplicationController@save_approval')->name('credit-applications.save_approval');
Route::get('/credit-applications/deny/{credit_application}', 'CreditApplicationController@deny')->name('credit-applications.deny');
Route::post('/notify/overdue/' , 'NotificationController@sendNotification')->name('notify.overdue');
Route::get('/notify/history/' , 'NotificationController@history')->name('notify.history');

Route::resource('credit-applications', 'CreditApplicationController');
Route::resource('customers', 'CustomerController');
Route::resource('sales', 'SalesController');
Route::resource('products', 'ProductController');
Route::resource('staffs', 'StaffController');
Route::resource('payment', 'PaymentController');

Route::get('apply', 'ApplicationFormController@index')->name('apply_credit_application');//

/*Step 1  - customer */
Route::get('application-form/customer/register', 'ApplicationFormController@new_customer')->name('register_customer'); // new customer
Route::post('application-form/customer/register', 'ApplicationFormController@save_customer')->name('save_customer'); // new customer
Route::get('application-form/customer/search', 'ApplicationFormController@search_customer')->name('search_customer'); // existing customer , show search form

/*step 2 - actual application form */
Route::get('application-form/create/customer/{customer}', 'ApplicationFormController@show_credit_application')->name('show_credit_application'); // show credit application form
Route::post('application-form/create/customer/{customer}', 'ApplicationFormController@save_credit_application')->name('save_credit_application'); // save credit application form
/*Step 3 - collaterals */
Route::get('customer/{customer}/application-form/{credit_application}/collateral', 'ApplicationFormController@credit_application_collateral')->name('collateral_form'); // specify collateral for credit application
Route::post('customer/{customer}/application-form/{credit_application}/collateral', 'ApplicationFormController@save_application_collateral')->name('save_collateral_form'); // specify collateral for credit application
/*Step 4 - choose product */
Route::get('customer/{customer}/application-form/{credit_application}/choose-product', 'ApplicationFormController@choose_product')->name('choose_product'); // choose product
Route::post('application-form/{credit_application}/choose-product/{customer}', 'ApplicationFormController@save_product')->name('save_product'); // choose product
/*step 5 - computation breakdown */
Route::get('application-form/{credit_application}/computation-breakdown/{customer}', 'ApplicationFormController@computation_breakdown')->name('computation_breakdown');
Route::post('application-form/{credit_application}/computation-breakdown/{customer}', 'ApplicationFormController@save_computation_breakdown')->name('save_computation_breakdown');

/* step 6 - co makers */
Route::get('application-form/{credit_application}/co-maker/{customer}', 'ApplicationFormController@co_makers')->name('co_makers'); // add comakers
Route::post('application-form/{credit_application}/co-maker/{customer}', 'ApplicationFormController@save_co_makers')->name('save_co_makers'); // add comakers

/* step 7 - map address */
Route::get('application-form/{credit_application}/map-address/{customer}', 'ApplicationFormController@map_address')->name('map_address'); // map address
Route::post('application-form/{credit_application}/map-address/{customer}', 'ApplicationFormController@save_map_address')->name('save_map_address'); // map address

/* step 8 - staff who handled the processing */
Route::get('application-form/{credit_application}/assisting-staff/{customer}', 'ApplicationFormController@assisting_staff')->name('assisting_staff');
Route::post('application-form/{credit_application}/assisting-/{customer}', 'ApplicationFormController@save_assisting_staff')->name('save_assisting_staff');
/* step 9 - branch manager notes */
Route::get('application-form/{credit_application}/final-notes/{customer}', 'ApplicationFormController@final_notes')->name('final_notes');
Route::post('application-form/{credit_application}/final-notes/{customer}', 'ApplicationFormController@save_final_notes')->name('save_final_notes');

/* Wizard Done*/
Route::get('application-form/success', 'ApplicationFormController@application_done')->name("application_done");


Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);
});

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Forms\CreditApplication\ApprovalForm;
use App\Forms\PaymentForm;
use App\Notifier\DuePaymentSMSNotifier;
use App\PaymentHistory;
use App\Repository\PaymentRepository;
use App\Sale;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;

class PaymentController extends Controller
{
    private $paymentRepository;

    /**
     * PaymentController constructor.
     * @param $paymentRepository
     */
    public function __construct(PaymentRepository $paymentRepository)
    {
        $this->paymentRepository = $paymentRepository;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $payments = PaymentHistory::all();
        return view('payment.index')->with([
            'payments'=>$payments
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(FormBuilder $formBuilder)
    {
        $paymentForm = $formBuilder->create(Paymentform::class, [
            'method' => 'POST',
            'url' => route('payment.store')
        ]);
        return view('payment.make_payment')->with([
            'paymentForm' => $paymentForm
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'sale_id' => 'required',
            'amount' => 'required|min:0',
            'date_received' => '',
            'received_by' => ''
        ]);
        $sale = Sale::findOrFail($validatedData['sale_id']);
        /*reduce remaining balance */
        $updatedBalance = floatval($sale->remaining_balance);
        $sale->remaining_balance = $updatedBalance - floatval($validatedData['amount']);
        $sale->save();
        PaymentHistory::create($validatedData);


        return redirect(url()->previous())->with([
            'status' => 'Payment record created. '
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function overdue()
    {
        $overDuePayments = $this->paymentRepository->getOverDuePayments();


        return view('payment.over_due')->with([
            'overDuePayments'=>$overDuePayments
        ]);
    }
//
//    public function send_due_notification(DuePaymentSMSNotifier $duePaymentSMSNotifier)
//    {
//        $username_api = setting('API_USERNAME');
//        $password_api = setting('API_PASSWORD');
//        $duePaymentSMSNotifier->setCredential($username_api, $password_api);
//
//
//        /* @TODO - get all overdued payment */
//        /* foreach  customer  , get their mobile number*/
//        /* prepare message  */
//        /* send message */
//        $duePaymentSMSNotifier->send();
//    }
}

resources/views/payment/index.blade.php
@extends('layouts.app', [
    'namePage' => 'Payments',
    'namePageLink' => route('payment.overdue'),
    'class' => 'sidebar-mini',
    'activePage' => 'payment.index',
    'backgroundImage' => "/images/honda_logo.png",
  ])

@push('js')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#payment-table').DataTable();
        });
    </script>
@endpush
@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="card">
                    <div class="card-header">
                        @include('alerts.success')
                        <h4 class="card-title">
                            <p class="float-left mt-2">
                                <a href="{{ route('payment.create') }}" class="btn btn-sm btn-primary">
                                    Make Payment
                                </a>
                            </p>
                            <p class="float-right mt-2">
                                <a href="{{ route('payment.overdue') }}" class="btn btn-sm btn-primary">
                                    Overdue
                                </a>
                            </p>

                            <div class="clearfix"></div>
                        </h4>
                    </div>
                    <div class="card-body">

                        <div class="table-responsive">
                            <table class="table" id="payment-table">
                                <thead class=" text-primary">
                                <th>
                                    Customer
                                </th>
                                <th>
                                    Payment
                                </th>
                                <th>Received by</th>
                                <th>
                                    Date
                                </th>
                                </thead>
                                <tbody>
                                @foreach($payments as $currentPayment)
                                    <tr>
                                        <td>
                                            {{ $currentPayment->getCustomer()->getFullName()  }}
                                        </td>
                                        <td>
                                            {{ $currentPayment->amount  }}
                                        </td>
                                        <td>
                                            {{ $currentPayment->getStaff()->getFullName()  }}
                                        </td>
                                        <td>
                                            {{ $currentPayment->date_received->format("F d.Y") }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/payment/make_payment.blade.php
@extends('layouts.app', [
    'namePage' => 'Credit Applications',
    'namePageLink' => route('payment.index'),
    'class' => 'sidebar-mini',
    'activePage' => 'payment.index',
    'backgroundImage' => "/images/honda_logo.png",
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        @include('alerts.success')
                        <div class="row">
                            <div class="col-1"></div>
                            <div class="col-10">
                                <legend>Make Payment</legend>
                                <form method="POST"
                                      action="{{ route('payment.store') }}"
                                      class="row text-left">
                                    @csrf
                                    {!! form($paymentForm) !!}
                                </form>
                            </div>
                            <div class="col-1"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection


@push('js')
    <script type="text/javascript">
        jQuery("select[name='sale_id']").selectize({});
    </script>

@endpush

resources/views/payment/over_due.blade.php
@extends('layouts.app', [
    'namePage' => 'Payments',
    'namePageLink' => route('payment.overdue'),
    'class' => 'sidebar-mini',
    'activePage' => 'due.payment',
    'backgroundImage' => "/images/honda_logo.png",
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        @include('alerts.success')
                        <h4 class="card-title">Overdue Accounts</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>
                                    Customer
                                </th>
                                <th>
                                    Address
                                </th>
                                <th>
                                    Phone
                                </th>
                                <th>
                                    Overdue Date
                                </th>
                                <th class="text-center">
                                    Action
                                </th>

                                </thead>
                                <tbody>
                                @foreach($overDuePayments as $currentOverdueSale)
                                    @php
                                        $currentSale = $currentOverdueSale['sale'];
                                        $overdueDate = $currentOverdueSale['overdue_date'];
                                        $currentCustomer = $currentSale->getCustomer();
                                        $product = $currentSale->getProduct();
                                    @endphp
                                    <tr>
                                        <td>
                                            {{ sprintf("%s %s %s %s",$currentCustomer->title , $currentCustomer->first_name , $currentCustomer->middle_name,$currentCustomer->last_name)  }}
                                        </td>
                                        <td>
                                            {{
                                            sprintf(
                                                "%s %s %s %s %s %s" ,
                                                $currentCustomer->house_number ,
                                                $currentCustomer->street ,
                                                $currentCustomer->barangay ,
                                                $currentCustomer->municipality ,
                                                $currentCustomer->province ,
                                                $currentCustomer->zipcode
                                            )
                                            }}
                                        </td>
                                        <td>
                                            {{ $currentCustomer->mobile_number  }}
                                        </td>
                                        <td>
                                            {{ $overdueDate }}
                                        </td>
                                        <td>
                                            <form action="{{route('notify.overdue')}}" method="POST">
                                                @csrf
                                                <input type="hidden" name="overdue_date" value="{{$overdueDate}}">
                                                <input type="hidden" name="product_id" value="{{$product->id}}">
                                                <input type="hidden" name="customer_id" value="{{$currentCustomer->id}}">
                                                <input type="submit" name="submit" value="Send Notification" class="btn btn-primary">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection