routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/payment/overdue', 'PaymentController@overdue')->name("payment.overdue");
Route::get('/credit-applications/pending', 'CreditApplicationController@pending')->name('credit-applications.pending');
Route::get('/credit-applications/approve/{credit_application}', 'CreditApplicationController@approve')->name('credit-applications.approve');
Route::post('/credit-applications/approve/{credit_application}/success', 'CreditApplicationController@save_approval')->name('credit-applications.save_approval');
Route::get('/credit-applications/deny/{credit_application}', 'CreditApplicationController@deny')->name('credit-applications.deny');
Route::post('/notify/overdue/' , 'NotificationController@sendNotification')->name('notify.overdue');
Route::get('/notify/history/' , 'NotificationController@history')->name('notify.history');

Route::resource('credit-applications', 'CreditApplicationController');
Route::resource('customers', 'CustomerController');
Route::resource('sales', 'SalesController');
Route::resource('products', 'ProductController');
Route::resource('staffs', 'StaffController');
Route::resource('payment', 'PaymentController');

Route::get('apply', 'ApplicationFormController@index')->name('apply_credit_application');//

/*Step 1  - customer */
Route::get('application-form/customer/register', 'ApplicationFormController@new_customer')->name('register_customer'); // new customer
Route::post('application-form/customer/register', 'ApplicationFormController@save_customer')->name('save_customer'); // new customer
Route::get('application-form/customer/search', 'ApplicationFormController@search_customer')->name('search_customer'); // existing customer , show search form

/*step 2 - actual application form */
Route::get('application-form/create/customer/{customer}', 'ApplicationFormController@show_credit_application')->name('show_credit_application'); // show credit application form
Route::post('application-form/create/customer/{customer}', 'ApplicationFormController@save_credit_application')->name('save_credit_application'); // save credit application form
/*Step 3 - collaterals */
Route::get('customer/{customer}/application-form/{credit_application}/collateral', 'ApplicationFormController@credit_application_collateral')->name('collateral_form'); // specify collateral for credit application
Route::post('customer/{customer}/application-form/{credit_application}/collateral', 'ApplicationFormController@save_application_collateral')->name('save_collateral_form'); // specify collateral for credit application
/*Step 4 - choose product */
Route::get('customer/{customer}/application-form/{credit_application}/choose-product', 'ApplicationFormController@choose_product')->name('choose_product'); // choose product
Route::post('application-form/{credit_application}/choose-product/{customer}', 'ApplicationFormController@save_product')->name('save_product'); // choose product
/*step 5 - computation breakdown */
Route::get('application-form/{credit_application}/computation-breakdown/{customer}', 'ApplicationFormController@computation_breakdown')->name('computation_breakdown');
Route::post('application-form/{credit_application}/computation-breakdown/{customer}', 'ApplicationFormController@save_computation_breakdown')->name('save_computation_breakdown');

/* step 6 - co makers */
Route::get('application-form/{credit_application}/co-maker/{customer}', 'ApplicationFormController@co_makers')->name('co_makers'); // add comakers
Route::post('application-form/{credit_application}/co-maker/{customer}', 'ApplicationFormController@save_co_makers')->name('save_co_makers'); // add comakers

/* step 7 - map address */
Route::get('application-form/{credit_application}/map-address/{customer}', 'ApplicationFormController@map_address')->name('map_address'); // map address
Route::post('application-form/{credit_application}/map-address/{customer}', 'ApplicationFormController@save_map_address')->name('save_map_address'); // map address

/* step 8 - staff who handled the processing */
Route::get('application-form/{credit_application}/assisting-staff/{customer}', 'ApplicationFormController@assisting_staff')->name('assisting_staff');
Route::post('application-form/{credit_application}/assisting-/{customer}', 'ApplicationFormController@save_assisting_staff')->name('save_assisting_staff');
/* step 9 - branch manager notes */
Route::get('application-form/{credit_application}/final-notes/{customer}', 'ApplicationFormController@final_notes')->name('final_notes');
Route::post('application-form/{credit_application}/final-notes/{customer}', 'ApplicationFormController@save_final_notes')->name('save_final_notes');

/* Wizard Done*/
Route::get('application-form/success', 'ApplicationFormController@application_done')->name("application_done");


Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];

    public function credit_application()
    {
        return $this->hasMany(CreditApplication::class);
    }

    public function credit_application_product()
    {
        return $this->hasMany(CreditApplicationProduct::class);
    }

    public function sale()
    {
        return $this->hasMany(Sale::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Forms\CreateProductForm;
use App\Forms\StaffForm;
use App\Forms\UpdateProductForm;
use App\Forms\UpdateStaffForm;
use App\Product;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allProducts = Product::all();
        return view('products.index')->with(compact('allProducts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(FormBuilder $formBuilder)
    {
        $createProductForm = $formBuilder->create(CreateProductForm::class, [
            'method' => 'POST',
            'enctype' => "multipart/form-data",
            'url' => route('products.store')
        ]);

        return view('products.create')->with(compact('createProductForm'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'description' => ' ',
            'type' => 'required',
            'picture' => 'required|file',
            'specification' => ' '
        ]);

        $uploadedFile = $validatedData['picture'];
        $fileName = $uploadedFile->getClientOriginalName();
        $uploadedFile->move(storage_path("app/public"), $uploadedFile->getClientOriginalName());
        $product = new Product();
        $product->name = $validatedData['name'];
        $product->description = $validatedData['description'];
        $product->type = $validatedData['type'];
        $product->specification = $validatedData['specification'];
        $product->picture = $fileName;
        $product->save();

        return redirect(url()->previous())->with(['status' => 'Product created']);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $productDetails = $product->toArray();
        unset($productDetails['id']);


        return view('products.show')->with(compact('product', 'productDetails'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product, FormBuilder $formBuilder)
    {
        $updateProductForm = $formBuilder->create(UpdateProductForm::class, [
            'method' => 'POST',
            'model' => $product,
            'url' => route('products.update', ['product' => $product])
        ]);

        return view('products.edit')->with(compact('product', 'updateProductForm'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $validatedData = $request->validate([
            "name" => "required",
            "description" => " ",
            "price" => " ",
            "type" => "required",
            "picture" => "file",
            "specification" => " ",
            "created_at" => " ",
            "updated_at" => " ",
        ]);
        if (isset($validatedData['picture'])) {
            $uploadedFile = $validatedData['picture'];
            $fileName = $uploadedFile->getClientOriginalName();
            $uploadedFile->move(storage_path("app/public"), $uploadedFile->getClientOriginalName());
            $product->picture = $fileName;
        }
        $product->name = $validatedData['name'];
        $product->description = $validatedData['description'];
        $product->type = $validatedData['type'];
        $product->specification = $validatedData['specification'];
        $product->price = $validatedData['price'];
        $product->save();

        return redirect(url()->previous())->with(['status' => 'Product information updated']);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->forceDelete();
        return redirect(url()->previous());
    }
}

resources/views/products/create.blade.php
@extends('layouts.app', [
    'namePage' => 'Products',
    'namePageLink' => route('products.index'),
    'class' => 'sidebar-mini',
    'activePage' => 'product',
    'backgroundImage' => "/images/honda_logo.png",
])

@section('content')
    <div class="panel-header panel-header-md">
        <h1 class="text-white text-center">{{ __('Create new product') }}</h1>
    </div>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12 mr-auto">
                    <br>
                    <div class="card card-signup text-center">
                        <div class="card-header ">

                        </div>
                        <div class="card-body">
                            @include('alerts.success')
                            <br>
                            <form method="POST" action="{{ route('products.store') }}" class="row text-left" enctype="multipart/form-data">
                                @csrf
                                {!! form($createProductForm) !!}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app', [
    'namePage' => 'Back',
    'namePageLink' => route('products.index'),
    'activePage' => 'product',
    'backgroundImage' => "/images/honda_logo.png",
])

@section('content')
    <div class="panel-header panel-header-md">
        <h1 class="text-white text-center">{{ __('Update Product') }}</h1>
    </div>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12 mr-auto">
                    <br>
                    <div class="card card-signup text-center">
                        <div class="card-header ">
                        </div>
                        <div class="card-body">
                            @include('alerts.success')
                            <br>
                            <form method="POST" action="{{ route('products.update',['product'=>$product]) }}" class="row text-left" enctype="multipart/form-data">
                                @csrf
                                @method("PUT")
                                {!! form($updateProductForm) !!}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app', [
    'namePage' => 'Products',
    'namePageLink' => route('products.index'),
    'class' => 'sidebar-mini',
    'activePage' => 'product',
    'backgroundImage' => "/images/honda_logo.png",
  ])
@push('js')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#product-table').DataTable();
        });
    </script>
@endpush
@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            <p class="float-left mt-2">
                                Products
                            </p>
                            <a href="{{route('products.create')}}" class="btn btn-sm btn-primary float-right">
                                Add new
                            </a>
                            <div class="clearfix"></div>
                        </h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="product-table">
                                <thead class=" text-primary">
                                <th>
                                    Picture
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Price
                                </th>
                                <th>
                                    Description
                                </th>
                                <th>
                                    Type
                                </th>
                                <th>
                                    Action
                                </th>
                                </thead>
                                <tbody>
                                @foreach($allProducts as $currentProduct)
                                    <tr>
                                        <td class="img-container" style="width: 250px">
                                            <img src="{{asset('storage/'.$currentProduct->picture)}}" alt="" class="img img-thumbnail">
                                        </td>
                                        <td>
                                            {{ $currentProduct->name  }}
                                        </td>
                                        <td>
                                            {{ $currentProduct->price  }}
                                        </td>
                                        <td>
                                            {{ $currentProduct->description  }}
                                        </td>
                                        <td>
                                            {{ $currentProduct->type  }}
                                        </td>
                                        <td>
                                            <a href="{{route('products.show',['product'=>$currentProduct])}}">View</a> |
                                            <a href="{{route('products.edit',['product'=>$currentProduct])}}">Update</a> |
                                            <a href="#" class="delete-staff-link">Delete</a>
                                            <form class="{{$currentProduct->id}}_delete" action="{{route('products.destroy',['product'=>$currentProduct])}}" method="POST" >
                                                @csrf
                                                @method('delete')
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            jQuery(".delete-staff-link").click(function(event) {
                event.preventDefault();
                if (confirm("Are you sure you want to continue ?")) {
                    jQuery(this).parent().find("form").submit();
                }
            });
        });
    </script>
@endpush

resources/views/products/show.blade.php
@extends('layouts.app', [
    'namePage' => 'Products',
    'namePageLink' => route("products.index"),
    'class' => 'sidebar-mini',
    'activePage' => 'product',
    'backgroundImage' => "/images/honda_logo.png",
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">View Product</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive table-bordered">
                            <img src="{{asset('storage/'.$productDetails['picture'])}}" alt="" class="img img-thumbnail">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <td>
                                        Name
                                    </td>
                                    <td>
                                        {{ $product->name  }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Description
                                    </td>
                                    <td>
                                        {{ $product->description  }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        Specification
                                    </td>
                                    <td>
                                        {{ $product->specification  }}
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection