routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/payment/overdue', 'PaymentController@overdue')->name("payment.overdue");
Route::get('/credit-applications/pending', 'CreditApplicationController@pending')->name('credit-applications.pending');
Route::get('/credit-applications/approve/{credit_application}', 'CreditApplicationController@approve')->name('credit-applications.approve');
Route::post('/credit-applications/approve/{credit_application}/success', 'CreditApplicationController@save_approval')->name('credit-applications.save_approval');
Route::get('/credit-applications/deny/{credit_application}', 'CreditApplicationController@deny')->name('credit-applications.deny');
Route::post('/notify/overdue/' , 'NotificationController@sendNotification')->name('notify.overdue');
Route::get('/notify/history/' , 'NotificationController@history')->name('notify.history');

Route::resource('credit-applications', 'CreditApplicationController');
Route::resource('customers', 'CustomerController');
Route::resource('sales', 'SalesController');
Route::resource('products', 'ProductController');
Route::resource('staffs', 'StaffController');
Route::resource('payment', 'PaymentController');

Route::get('apply', 'ApplicationFormController@index')->name('apply_credit_application');//

/*Step 1  - customer */
Route::get('application-form/customer/register', 'ApplicationFormController@new_customer')->name('register_customer'); // new customer
Route::post('application-form/customer/register', 'ApplicationFormController@save_customer')->name('save_customer'); // new customer
Route::get('application-form/customer/search', 'ApplicationFormController@search_customer')->name('search_customer'); // existing customer , show search form

/*step 2 - actual application form */
Route::get('application-form/create/customer/{customer}', 'ApplicationFormController@show_credit_application')->name('show_credit_application'); // show credit application form
Route::post('application-form/create/customer/{customer}', 'ApplicationFormController@save_credit_application')->name('save_credit_application'); // save credit application form
/*Step 3 - collaterals */
Route::get('customer/{customer}/application-form/{credit_application}/collateral', 'ApplicationFormController@credit_application_collateral')->name('collateral_form'); // specify collateral for credit application
Route::post('customer/{customer}/application-form/{credit_application}/collateral', 'ApplicationFormController@save_application_collateral')->name('save_collateral_form'); // specify collateral for credit application
/*Step 4 - choose product */
Route::get('customer/{customer}/application-form/{credit_application}/choose-product', 'ApplicationFormController@choose_product')->name('choose_product'); // choose product
Route::post('application-form/{credit_application}/choose-product/{customer}', 'ApplicationFormController@save_product')->name('save_product'); // choose product
/*step 5 - computation breakdown */
Route::get('application-form/{credit_application}/computation-breakdown/{customer}', 'ApplicationFormController@computation_breakdown')->name('computation_breakdown');
Route::post('application-form/{credit_application}/computation-breakdown/{customer}', 'ApplicationFormController@save_computation_breakdown')->name('save_computation_breakdown');

/* step 6 - co makers */
Route::get('application-form/{credit_application}/co-maker/{customer}', 'ApplicationFormController@co_makers')->name('co_makers'); // add comakers
Route::post('application-form/{credit_application}/co-maker/{customer}', 'ApplicationFormController@save_co_makers')->name('save_co_makers'); // add comakers

/* step 7 - map address */
Route::get('application-form/{credit_application}/map-address/{customer}', 'ApplicationFormController@map_address')->name('map_address'); // map address
Route::post('application-form/{credit_application}/map-address/{customer}', 'ApplicationFormController@save_map_address')->name('save_map_address'); // map address

/* step 8 - staff who handled the processing */
Route::get('application-form/{credit_application}/assisting-staff/{customer}', 'ApplicationFormController@assisting_staff')->name('assisting_staff');
Route::post('application-form/{credit_application}/assisting-/{customer}', 'ApplicationFormController@save_assisting_staff')->name('save_assisting_staff');
/* step 9 - branch manager notes */
Route::get('application-form/{credit_application}/final-notes/{customer}', 'ApplicationFormController@final_notes')->name('final_notes');
Route::post('application-form/{credit_application}/final-notes/{customer}', 'ApplicationFormController@save_final_notes')->name('save_final_notes');

/* Wizard Done*/
Route::get('application-form/success', 'ApplicationFormController@application_done')->name("application_done");


Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);
});

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Sale extends Model
{
    const STATUS_APPROVED = 'approved';
    protected $guarded = [];

    public function credit_application()
    {
        return $this->belongsTo(CreditApplication::class, 'credit_application');
    }

    public function payment_history()
    {
        return $this->hasMany(PaymentHistory::class);
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function getLastPaymentHistory()
    {
        return PaymentHistory::where([
            'sale_id' => $this->id
        ])->get()->last();
    }

    public function getCreditApplication()
    {
        return CreditApplication::find($this->credit_application_id)->firstOrFail();
    }

    public function getProduct()
    {
        $sqlQuery = <<<EOL
        SELECT
        products.id,
        products.`name`,
        products.description,
        products.type,
        products.picture,
        products.specification,
        products.created_at,
        products.updated_at,
        products.price
        FROM
        sales
        INNER JOIN credit_applications ON sales.credit_application_id = credit_applications.id
        INNER JOIN products ON sales.product_id = products.id
        WHERE
        sales.id = :sale_id
EOL;
        $res = Db::select(DB::raw($sqlQuery), ['sale_id' => $this->id]);
        if (isset($res[0])) {
            return $res[0];
        }else{
            return new NullProduct();
        }
    }

    public function getCustomer()
    {

        $sqlQuery = <<<EOL
        SELECT
        customers.id,
        customers.title,
        customers.first_name,
        customers.middle_name,
        customers.last_name,
        customers.suffix,
        customers.birthday,
        customers.mobile_number,
        customers.zipcode,
        customers.province,
        customers.municipality,
        customers.barangay,
        customers.street,
        customers.house_number,
        customers.wedding_anniversary,
        customers.civil_status,
        customers.facebook_account
        FROM
        credit_applications
        INNER JOIN customers ON credit_applications.customer_id = customers.id
        INNER JOIN sales ON sales.credit_application_id = credit_applications.id
        WHERE
        sales.id = :sale_id
EOL;
        $res = Db::select(DB::raw($sqlQuery), ['sale_id' => $this->id]);
        if (isset($res[0])) {
            return $res[0];
        }else{
            return new NullCustomer();
        }
    }

}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use App\CreditApplication;
use App\Sale;
use Illuminate\Http\Request;

class SalesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allSales = Sale::orderBy("id","DESC")->get();

        return view('sales.index')->with(compact('allSales'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function show(Sale $sale)
    {
        $sale->total_amount = 'P ' . number_format($sale->total_amount, 2);
        $sale->tax = 'P ' . number_format($sale->tax, 2);
        $sale->tax_rate = number_format($sale->tax_rate, 2);
        $salesInfo = $sale->toArray();
        unset($salesInfo['id']);
        unset($salesInfo['credit_application']);
        unset($salesInfo['credit_application']);
        unset($salesInfo['credit_application']);
        return view('sales.show')->with(compact('salesInfo','sale'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function edit(Sale $sale)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sale $sale)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sale  $sale
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sale $sale)
    {
        //
    }
}

resources/views/sales/index.blade.php
@extends('layouts.app', [
    'namePage' => 'Sales',
    'namePageLink' => route('sales.index'),
    'class' => 'sidebar-mini',
    'activePage' => 'sale',
    'backgroundImage' => "/images/honda_logo.png",
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Sales</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th>
                                    #
                                </th>
                                <th>
                                    Customer
                                </th>
                                <th>
                                    Tax
                                </th>
                                <th>
                                    Total Amount
                                </th>
                                <th>
                                    Status
                                </th>
                                </thead>
                                <tbody>
                                @foreach($allSales as $currentSale)
                                    <tr>
                                        <td>
                                            {{ $currentSale->id  }}
                                        </td>
                                        <td>
                                            <a href="{{route('customers.show',['customer'=>$currentSale->getCreditApplication()->customer])}}">
                                                {{ $currentSale->getCreditApplication()->customer->getFullName()  }}
                                            </a>
                                        </td>
                                        <td>
                                            % {{ number_format($currentSale->tax_rate,2) }}
                                        </td>
                                        <td>
                                            P {{ number_format($currentSale->total_amount,2) }}
                                        </td>
                                        <td>
                                            {{ $currentSale->status }}
                                        </td>
                                        <td>
                                            <a href="{{route('sales.show',['sale'=>$currentSale])}}">Other Information</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sales/show.blade.php
@extends('layouts.app', [
    'namePage' => 'View Customer',
    'namePageLink' => route("customers.index"),
    'class' => 'sidebar-mini',
    'activePage' => 'customers',
    'backgroundImage' => "/images/honda_logo.png",
  ])

@section('content')
    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">View Customer</h4>
                    </div>
                    <div class="card-body">
                        <a class="btn btn-info" href="{{route('credit-applications.show',['credit_application'=>$sale->credit_application])}}">View Credit Application Info</a>
                        <div class="table-responsive table-bordered">
                            <table class="table">
                                <tbody>
                                @foreach($salesInfo as $key=>$val)
                                    <tr>
                                        <td>
                                            {{ \App\Helpers\StringHelper::labelify($key) }}
                                        </td>
                                        <td>
                                            {{ $sale->$key  }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sales/update.blade.php
@extends('layouts.app', [
    'namePage' => 'Back',
    'namePageLink' => route('customers.index'),
    'activePage' => 'register',
    'backgroundImage' => "/images/honda_logo.png",
])

@section('content')
    <div class="panel-header panel-header-md">
        <h1 class="text-white text-center">{{ __('Update Customer') }}</h1>
    </div>
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12 mr-auto">
                    <br>
                    <div class="card card-signup text-center">
                        <div class="card-header ">
                        </div>
                        <div class="card-body">
                            @include('alerts.success')
                            <br>
                            <form method="POST" action="{{ route('customers.update',['customer'=>$customer]) }}" class="row text-left">
                                @csrf
                                @method("PUT")
                                {!! form($customerForm) !!}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection